name: Auto Commit

on:
  push:
    branches:
      - main
      
  schedule:
  - cron: "0 7-11 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email ${{ secrets.GIT_USER_EMAIL }}
          git config --local user.name "kylejb"
          git add .
          
          arr[0]="auto commit"
          arr[1]="auto commit"
          arr[2]="auto commit"
          arr[3]="auto commit"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}